CREATE DATABASE IF NOT EXISTS `master_chief` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `master_chief`;

CREATE TABLE `RECIPES` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(63),
  `category` VARCHAR(63),
  `preparation_time` INT,
  `cooking_time` INT,
  `person_nb` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INGREDIENTS` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(63),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `STEPS` (
  `id` INT(11) NOT NULL,
  `description` LONGTEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TOOLS` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(63),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `STOCKS` (
  `id` INT(11) NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` INT,
  `arrived_at` DATE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INGREDIENT_RECIPE` (
  `id` INT(11) NOT NULL,
  `ingredient_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `quantity` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_STEP` (
  `id` INT(11) NOT NULL,
  `recipe_id` INT NOT NULL,
  `step_id` INT NOT NULL,
  `order` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_TOOL` (
  `id` INT(11) NOT NULL,
  `recipe_id` VARCHAR(42),
  `tool_id` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `STOCKS` ADD FOREIGN KEY (`ingredient_id`) REFERENCES `INGREDIENTS` (`id`);
ALTER TABLE `INGREDIENT_RECIPE` ADD FOREIGN KEY (`ingredient_id`) REFERENCES `INGREDIENTS` (`id`);
ALTER TABLE `INGREDIENT_RECIPE` ADD FOREIGN KEY (`recipe_id`) REFERENCES `RECIPES` (`id`);
ALTER TABLE `RECIPE_STEP` ADD FOREIGN KEY (`step_id`) REFERENCES `STEPS` (`id`);
ALTER TABLE `RECIPE_STEP` ADD FOREIGN KEY (`recipe_id`) REFERENCES `RECIPES` (`id`);
ALTER TABLE `RECIPE_TOOL` ADD FOREIGN KEY (`tool_id`) REFERENCES `TOOLS` (`id`);
ALTER TABLE `RECIPE_TOOL` ADD FOREIGN KEY (`recipe_id`) REFERENCES `RECIPES` (`id`);